### ISSUE TITLE
Few issues in Evolver RK.ipynb

### ISSUE THREAD

**Issue by ThomasTram** [samgrund/cosmology-project-AU-21#3]
Hi

Evolver RK looks really good, nice work! However, I noticed a few mistakes and some things that can be improved:

The ODE for growth, 
```python
def dudt(t, p):
    H = dadt(t,p)/p[2]
    return 3/2 * H**2 * omega0M * p[0] - 2*H*p[1]
```

seems wrong. Probably `omega0M` should really be the dreaded time-dependent function $\Omega_m(a)$ as defined by Ryden. I think the substitution should be `H**2 * omega0M` -> `omega0M/p[2]**3` where we are using units of $H_0^{-1}$. But please check against Rydens definition.

The initial time,
```python
tstart   = 1/(np.sqrt(omega0R)*70) * 1/2 * astart**2
```
has a small error. The "70" should be removed, since we are using units of $H_0^{-1}$. Furthermore, this relation assumes radiation domination, so it is probably better to set `a_start` to something even lower, perhaps 1e-7.

When initialising a model in CLASSpp, there are two options:
Either initialise on construction (preferred method) like this:
```python
Omega_b = 0.05
cosmo = Class({'Omega_b':Omega_b, 'Omega_cdm':omega0M - Omega_b, 'H0':70})
```
or initialise CLASS with the default model, call the `.set()` method repeatedly with a final call to `.compute()`:
```python
cosmo = Class()
Omega_b = 0.05
cosmo.set({'Omega_b':Omega_b, 'Omega_cdm':omega0M - Omega_b, 'H0':70})
cosmo.compute()
```
Without the final compute, CLASS was using default values for $H_0$ and $\Omega_m$. (I think I might be responsible for introducing that mistake in your notebook!)

Now everything is working I think. There are a few more points however:

- To properly normalise delta(a), you need to divide by the value of delta(a) *today*, i.e. delta(a==1). The easiest way to get it is to interpolate. Something like `np.interp(1, yvals[:,2], yvals[:,0]`. (Spline interpolation with scipy is also an option.)
- `tstop` should be set to a value larger than 1 to make sure that a=1 is part of the solution output.

Cheers,
Thomas

**Comment by samgrund** [comment]
I believe all points should be fixed in the new version of RK-solver 😎
