### ISSUE TITLE
Critical bug in Evolver RK

### ISSUE THREAD

**Issue by ThomasTram** [samgrund/cosmology-project-AU-21#4]
Hi

I just checked the growth equation, and it did not work at all. The problem is in the implementation of RK4. Consider this loop:

```python
        for (j,dydt) in enumerate(dydts):
            k1 = dt * dydt(ts[i],yvals[i])
            k2 = dt * dydt(ts[i] + dt/2, yvals[i] + k1/2)
            k3 = dt * dydt(ts[i] + dt/2, yvals[i] + k2/2)
            k4 = dt * dydt(ts[i] + dt, yvals[i] + k3)
            yn[j] = yn[j] + k1/6 + k2/3 + k3/3 + k4/6
```
dydt depends on the full solution vector in yvals but returns only a single value. That means that a sum like `yvals[i] + k1/2` adds k1/2 to **all** entries in yvals[i] before sending it to the function! Thus, when dudt needs access to a = p[2], p[2] is completely wrong! The Friedmann equation is still OK however, since it does not depend on other values.

One might then choose to construct a temporary variable ytmp which is a .copy() of yvals[i] with k1/2 added on the j'th position. However, that is still not ideal, since the "intermediate" values would not all be updated at the same time.

The most elegant way to solve this problem is to create a function that returns the full dydt array. Then k_i become proper arrays of the same size as y, and the inner loop can be eliminated completely.

It is also possible to remove the two np.delete statements in RK4 and simply make the assignment in the outer loop like this:
```python
yvals[i + 1] = yvals[i] + k1/6 + k2/3 + k3/3 + k4/6
```
If yvals[0] is initialised to p0, you can also get rid of yn completely. 👍 

Let me know if this makes sense!

Cheers,
Thomas

**Comment by samgrund** [comment]
Great that you noticed this! It explains a lot, and makes a lot of sense. Will be fixed asap!

**Comment by samgrund** [comment]
Fixed the problem considering the suggestions you made. Works great now!
